version: '3.8'
services:
  php-apache:
    image: php:8.1-apache
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./apache-config/custom.conf:/etc/apache2/conf-available/custom.conf
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "a2enconf custom && apache2-foreground"
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_web1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./database/app_web1_20220610.sql:/docker-entrypoint-initdb.d/app_web1_20220610.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
volumes:
  db-data:
